---
title: "9.5 Financial Data"
author: "Christopher Farrar"
date: "July 23, 2016"
output: 
  html_document:
  keep_md: true
---
### MMC is my Financial Data
## setup
```{r}

library(tseries)

MyData <- get.hist.quote("mmc", quote = "Close")

length(MyData)

MyData_Ret <- log(lag(MyData)) - log(MyData)

length(MyData_Ret)
```
### Decay Factors
```{r}
MyData_Vol <- sd(MyData_Ret) * sqrt(250) * 100
summary(MyData_Vol)
class(MyData_Vol)
```
### Volume function
```{r}
Volume <- function(d, logreturns) {
 var = 0
 var1 = 0
 varlist <- c()
 for (r in logreturns){
 var1 = var1*(1 - 1/d) + 1
 var = (1 - 1/var1) * var + (1 / var1)*r^2
 varlist <- c(varlist,var)
 }
 sqrt(varlist)}
Volume1 <- Volume(10,MyData_Ret)
Volume2 <- Volume(30,MyData_Ret)
Volume3 <- Volume(100,MyData_Ret)
plot(Volume1, type = "l")
lines(Volume3,type = "l", col = "blue")

```

## Summary
 It appears that there was two statistically significant spikes during the course MMC observation using closing percentages. This could be attributed during large swings in the stock market